#!/bin/bash

./wwf "$1" < tests/sh1 | cmp tests/sh1.out
./wwf "$1" < tests/sh2 | cmp tests/sh2.out
./wwf "$1" < tests/sh3 | cmp tests/sh3.out
./wwf "$1" < tests/t2 | cmp tests/t2.out
./wwf -c=wwf15 "$1" < tests/recbig | cmp tests/recbig.out
./wwf -c=wwf15 "$1" < tests/rec2 | cmp tests/rec2.out